//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KY_Soap_Test.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://HP.HPES.MED.Interfaces/Batch", ConfigurationName="ServiceReference1.BatchWebServiceInterface")]
    public interface BatchWebServiceInterface {
        
        // CODEGEN: Generating message contract since the operation SubmitFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://HP.HPES.MED.Interfaces/Batch/BatchWebServiceInterface/SubmitFile", ReplyAction="http://HP.HPES.MED.Interfaces/Batch/BatchWebServiceInterface/SubmitFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KY_Soap_Test.ServiceReference1.BatchSubmitTransactionResponse SubmitFile(KY_Soap_Test.ServiceReference1.BatchSubmitTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://HP.HPES.MED.Interfaces/Batch/BatchWebServiceInterface/SubmitFile", ReplyAction="http://HP.HPES.MED.Interfaces/Batch/BatchWebServiceInterface/SubmitFileResponse")]
        System.Threading.Tasks.Task<KY_Soap_Test.ServiceReference1.BatchSubmitTransactionResponse> SubmitFileAsync(KY_Soap_Test.ServiceReference1.BatchSubmitTransactionRequest request);
        
        // CODEGEN: Generating message contract since the operation DownloadFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://HP.HPES.MED.Interfaces/Batch/BatchWebServiceInterface/DownloadFile", ReplyAction="http://HP.HPES.MED.Interfaces/Batch/BatchWebServiceInterface/DownloadFileResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KY_Soap_Test.ServiceReference1.BatchResultsRetrievalTransactionResponse DownloadFile(KY_Soap_Test.ServiceReference1.BatchResultsRetrievalTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://HP.HPES.MED.Interfaces/Batch/BatchWebServiceInterface/DownloadFile", ReplyAction="http://HP.HPES.MED.Interfaces/Batch/BatchWebServiceInterface/DownloadFileResponse" +
            "")]
        System.Threading.Tasks.Task<KY_Soap_Test.ServiceReference1.BatchResultsRetrievalTransactionResponse> DownloadFileAsync(KY_Soap_Test.ServiceReference1.BatchResultsRetrievalTransactionRequest request);
        
        // CODEGEN: Generating message contract since the operation DownloadAckFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://HP.HPES.MED.Interfaces/Batch/BatchWebServiceInterface/DownloadAckFile", ReplyAction="http://HP.HPES.MED.Interfaces/Batch/BatchWebServiceInterface/DownloadAckFileRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KY_Soap_Test.ServiceReference1.BatchSubmitAckRetrievalTransactionResponse DownloadAckFile(KY_Soap_Test.ServiceReference1.BatchSubmitAckRetrievalTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://HP.HPES.MED.Interfaces/Batch/BatchWebServiceInterface/DownloadAckFile", ReplyAction="http://HP.HPES.MED.Interfaces/Batch/BatchWebServiceInterface/DownloadAckFileRespo" +
            "nse")]
        System.Threading.Tasks.Task<KY_Soap_Test.ServiceReference1.BatchSubmitAckRetrievalTransactionResponse> DownloadAckFileAsync(KY_Soap_Test.ServiceReference1.BatchSubmitAckRetrievalTransactionRequest request);
        
        // CODEGEN: Parameter 'GetDownloadFilesByPayloadIDResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://HP.HPES.MED.Interfaces/Batch/BatchWebServiceInterface/GetDownloadFilesByPa" +
            "yloadID", ReplyAction="http://HP.HPES.MED.Interfaces/Batch/BatchWebServiceInterface/GetDownloadFilesByPa" +
            "yloadIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KY_Soap_Test.ServiceReference1.GetDownloadFilesByPayloadIDResponse GetDownloadFilesByPayloadID(KY_Soap_Test.ServiceReference1.GetDownloadFilesByPayloadIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://HP.HPES.MED.Interfaces/Batch/BatchWebServiceInterface/GetDownloadFilesByPa" +
            "yloadID", ReplyAction="http://HP.HPES.MED.Interfaces/Batch/BatchWebServiceInterface/GetDownloadFilesByPa" +
            "yloadIDResponse")]
        System.Threading.Tasks.Task<KY_Soap_Test.ServiceReference1.GetDownloadFilesByPayloadIDResponse> GetDownloadFilesByPayloadIDAsync(KY_Soap_Test.ServiceReference1.GetDownloadFilesByPayloadIDRequest request);
        
        // CODEGEN: Parameter 'GetDownloadFilesByTPIDResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://HP.HPES.MED.Interfaces/Batch/BatchWebServiceInterface/GetDownloadFilesByTP" +
            "ID", ReplyAction="http://HP.HPES.MED.Interfaces/Batch/BatchWebServiceInterface/GetDownloadFilesByTP" +
            "IDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KY_Soap_Test.ServiceReference1.GetDownloadFilesByTPIDResponse GetDownloadFilesByTPID(KY_Soap_Test.ServiceReference1.GetDownloadFilesByTPIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://HP.HPES.MED.Interfaces/Batch/BatchWebServiceInterface/GetDownloadFilesByTP" +
            "ID", ReplyAction="http://HP.HPES.MED.Interfaces/Batch/BatchWebServiceInterface/GetDownloadFilesByTP" +
            "IDResponse")]
        System.Threading.Tasks.Task<KY_Soap_Test.ServiceReference1.GetDownloadFilesByTPIDResponse> GetDownloadFilesByTPIDAsync(KY_Soap_Test.ServiceReference1.GetDownloadFilesByTPIDRequest request);
        
        // CODEGEN: Parameter 'GetDownloadFilesByUserIDResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://HP.HPES.MED.Interfaces/Batch/BatchWebServiceInterface/GetDownloadFilesByUs" +
            "erID", ReplyAction="http://HP.HPES.MED.Interfaces/Batch/BatchWebServiceInterface/GetDownloadFilesByUs" +
            "erIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KY_Soap_Test.ServiceReference1.GetDownloadFilesByUserIDResponse GetDownloadFilesByUserID(KY_Soap_Test.ServiceReference1.GetDownloadFilesByUserIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://HP.HPES.MED.Interfaces/Batch/BatchWebServiceInterface/GetDownloadFilesByUs" +
            "erID", ReplyAction="http://HP.HPES.MED.Interfaces/Batch/BatchWebServiceInterface/GetDownloadFilesByUs" +
            "erIDResponse")]
        System.Threading.Tasks.Task<KY_Soap_Test.ServiceReference1.GetDownloadFilesByUserIDResponse> GetDownloadFilesByUserIDAsync(KY_Soap_Test.ServiceReference1.GetDownloadFilesByUserIDRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd")]
    public partial class CAQHRequestField : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string payloadTypeField;
        
        private string processingModeField;
        
        private string payloadIDField;
        
        private int payloadLengthField;
        
        private string timeStampField;
        
        private string senderIDField;
        
        private string receiverIDField;
        
        private string cORERuleVersionField;
        
        private string checkSumField;
        
        private byte[] payloadField;
        
        private string userNameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PayloadType {
            get {
                return this.payloadTypeField;
            }
            set {
                this.payloadTypeField = value;
                this.RaisePropertyChanged("PayloadType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ProcessingMode {
            get {
                return this.processingModeField;
            }
            set {
                this.processingModeField = value;
                this.RaisePropertyChanged("ProcessingMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PayloadID {
            get {
                return this.payloadIDField;
            }
            set {
                this.payloadIDField = value;
                this.RaisePropertyChanged("PayloadID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int PayloadLength {
            get {
                return this.payloadLengthField;
            }
            set {
                this.payloadLengthField = value;
                this.RaisePropertyChanged("PayloadLength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SenderID {
            get {
                return this.senderIDField;
            }
            set {
                this.senderIDField = value;
                this.RaisePropertyChanged("SenderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ReceiverID {
            get {
                return this.receiverIDField;
            }
            set {
                this.receiverIDField = value;
                this.RaisePropertyChanged("ReceiverID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CORERuleVersion {
            get {
                return this.cORERuleVersionField;
            }
            set {
                this.cORERuleVersionField = value;
                this.RaisePropertyChanged("CORERuleVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CheckSum {
            get {
                return this.checkSumField;
            }
            set {
                this.checkSumField = value;
                this.RaisePropertyChanged("CheckSum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=9)]
        public byte[] Payload {
            get {
                return this.payloadField;
            }
            set {
                this.payloadField = value;
                this.RaisePropertyChanged("Payload");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd")]
    public partial class CAQHResponseField : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string payloadTypeField;
        
        private string processingModeField;
        
        private string payloadIDField;
        
        private int payloadLengthField;
        
        private string timeStampField;
        
        private string senderIDField;
        
        private string receiverIDField;
        
        private string cORERuleVersionField;
        
        private string checkSumField;
        
        private byte[] payloadField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PayloadType {
            get {
                return this.payloadTypeField;
            }
            set {
                this.payloadTypeField = value;
                this.RaisePropertyChanged("PayloadType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ProcessingMode {
            get {
                return this.processingModeField;
            }
            set {
                this.processingModeField = value;
                this.RaisePropertyChanged("ProcessingMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PayloadID {
            get {
                return this.payloadIDField;
            }
            set {
                this.payloadIDField = value;
                this.RaisePropertyChanged("PayloadID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int PayloadLength {
            get {
                return this.payloadLengthField;
            }
            set {
                this.payloadLengthField = value;
                this.RaisePropertyChanged("PayloadLength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SenderID {
            get {
                return this.senderIDField;
            }
            set {
                this.senderIDField = value;
                this.RaisePropertyChanged("SenderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ReceiverID {
            get {
                return this.receiverIDField;
            }
            set {
                this.receiverIDField = value;
                this.RaisePropertyChanged("ReceiverID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CORERuleVersion {
            get {
                return this.cORERuleVersionField;
            }
            set {
                this.cORERuleVersionField = value;
                this.RaisePropertyChanged("CORERuleVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CheckSum {
            get {
                return this.checkSumField;
            }
            set {
                this.checkSumField = value;
                this.RaisePropertyChanged("CheckSum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=9)]
        public byte[] Payload {
            get {
                return this.payloadField;
            }
            set {
                this.payloadField = value;
                this.RaisePropertyChanged("Payload");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchSubmitTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", Order=0)]
        public KY_Soap_Test.ServiceReference1.CAQHRequestField COREEnvelopeBatchSubmission;
        
        public BatchSubmitTransactionRequest() {
        }
        
        public BatchSubmitTransactionRequest(KY_Soap_Test.ServiceReference1.CAQHRequestField COREEnvelopeBatchSubmission) {
            this.COREEnvelopeBatchSubmission = COREEnvelopeBatchSubmission;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchSubmitTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", Order=0)]
        public KY_Soap_Test.ServiceReference1.CAQHResponseField COREEnvelopeBatchSubmissionResponse;
        
        public BatchSubmitTransactionResponse() {
        }
        
        public BatchSubmitTransactionResponse(KY_Soap_Test.ServiceReference1.CAQHResponseField COREEnvelopeBatchSubmissionResponse) {
            this.COREEnvelopeBatchSubmissionResponse = COREEnvelopeBatchSubmissionResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchResultsRetrievalTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", Order=0)]
        public KY_Soap_Test.ServiceReference1.CAQHRequestField COREEnvelopeBatchResultsRetrievalRequest;
        
        public BatchResultsRetrievalTransactionRequest() {
        }
        
        public BatchResultsRetrievalTransactionRequest(KY_Soap_Test.ServiceReference1.CAQHRequestField COREEnvelopeBatchResultsRetrievalRequest) {
            this.COREEnvelopeBatchResultsRetrievalRequest = COREEnvelopeBatchResultsRetrievalRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchResultsRetrievalTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", Order=0)]
        public KY_Soap_Test.ServiceReference1.CAQHResponseField COREEnvelopeBatchResultsRetrievalResponse;
        
        public BatchResultsRetrievalTransactionResponse() {
        }
        
        public BatchResultsRetrievalTransactionResponse(KY_Soap_Test.ServiceReference1.CAQHResponseField COREEnvelopeBatchResultsRetrievalResponse) {
            this.COREEnvelopeBatchResultsRetrievalResponse = COREEnvelopeBatchResultsRetrievalResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchSubmitAckRetrievalTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", Order=0)]
        public KY_Soap_Test.ServiceReference1.CAQHRequestField COREEnvelopeBatchSubmissionAckRetrievalRequest;
        
        public BatchSubmitAckRetrievalTransactionRequest() {
        }
        
        public BatchSubmitAckRetrievalTransactionRequest(KY_Soap_Test.ServiceReference1.CAQHRequestField COREEnvelopeBatchSubmissionAckRetrievalRequest) {
            this.COREEnvelopeBatchSubmissionAckRetrievalRequest = COREEnvelopeBatchSubmissionAckRetrievalRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchSubmitAckRetrievalTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd", Order=0)]
        public KY_Soap_Test.ServiceReference1.CAQHResponseField COREEnvelopeBatchSubmissionAckRetrievalResponse;
        
        public BatchSubmitAckRetrievalTransactionResponse() {
        }
        
        public BatchSubmitAckRetrievalTransactionResponse(KY_Soap_Test.ServiceReference1.CAQHResponseField COREEnvelopeBatchSubmissionAckRetrievalResponse) {
            this.COREEnvelopeBatchSubmissionAckRetrievalResponse = COREEnvelopeBatchSubmissionAckRetrievalResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDownloadFilesByPayloadID", WrapperNamespace="http://HP.HPES.MED.Interfaces/Batch", IsWrapped=true)]
    public partial class GetDownloadFilesByPayloadIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://HP.HPES.MED.Interfaces/Batch", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PayloadID;
        
        public GetDownloadFilesByPayloadIDRequest() {
        }
        
        public GetDownloadFilesByPayloadIDRequest(string PayloadID) {
            this.PayloadID = PayloadID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDownloadFilesByPayloadIDResponse", WrapperNamespace="http://HP.HPES.MED.Interfaces/Batch", IsWrapped=true)]
    public partial class GetDownloadFilesByPayloadIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://HP.HPES.MED.Interfaces/Batch", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetDownloadFilesByPayloadIDResult;
        
        public GetDownloadFilesByPayloadIDResponse() {
        }
        
        public GetDownloadFilesByPayloadIDResponse(string GetDownloadFilesByPayloadIDResult) {
            this.GetDownloadFilesByPayloadIDResult = GetDownloadFilesByPayloadIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDownloadFilesByTPID", WrapperNamespace="http://HP.HPES.MED.Interfaces/Batch", IsWrapped=true)]
    public partial class GetDownloadFilesByTPIDRequest {
        
        public GetDownloadFilesByTPIDRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDownloadFilesByTPIDResponse", WrapperNamespace="http://HP.HPES.MED.Interfaces/Batch", IsWrapped=true)]
    public partial class GetDownloadFilesByTPIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://HP.HPES.MED.Interfaces/Batch", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetDownloadFilesByTPIDResult;
        
        public GetDownloadFilesByTPIDResponse() {
        }
        
        public GetDownloadFilesByTPIDResponse(string GetDownloadFilesByTPIDResult) {
            this.GetDownloadFilesByTPIDResult = GetDownloadFilesByTPIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDownloadFilesByUserID", WrapperNamespace="http://HP.HPES.MED.Interfaces/Batch", IsWrapped=true)]
    public partial class GetDownloadFilesByUserIDRequest {
        
        public GetDownloadFilesByUserIDRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDownloadFilesByUserIDResponse", WrapperNamespace="http://HP.HPES.MED.Interfaces/Batch", IsWrapped=true)]
    public partial class GetDownloadFilesByUserIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://HP.HPES.MED.Interfaces/Batch", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetDownloadFilesByUserIDResult;
        
        public GetDownloadFilesByUserIDResponse() {
        }
        
        public GetDownloadFilesByUserIDResponse(string GetDownloadFilesByUserIDResult) {
            this.GetDownloadFilesByUserIDResult = GetDownloadFilesByUserIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BatchWebServiceInterfaceChannel : KY_Soap_Test.ServiceReference1.BatchWebServiceInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BatchWebServiceInterfaceClient : System.ServiceModel.ClientBase<KY_Soap_Test.ServiceReference1.BatchWebServiceInterface>, KY_Soap_Test.ServiceReference1.BatchWebServiceInterface {
        
        public BatchWebServiceInterfaceClient() {
        }
        
        public BatchWebServiceInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BatchWebServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BatchWebServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BatchWebServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KY_Soap_Test.ServiceReference1.BatchSubmitTransactionResponse KY_Soap_Test.ServiceReference1.BatchWebServiceInterface.SubmitFile(KY_Soap_Test.ServiceReference1.BatchSubmitTransactionRequest request) {
            return base.Channel.SubmitFile(request);
        }
        
        public KY_Soap_Test.ServiceReference1.CAQHResponseField SubmitFile(KY_Soap_Test.ServiceReference1.CAQHRequestField COREEnvelopeBatchSubmission) {
            KY_Soap_Test.ServiceReference1.BatchSubmitTransactionRequest inValue = new KY_Soap_Test.ServiceReference1.BatchSubmitTransactionRequest();
            inValue.COREEnvelopeBatchSubmission = COREEnvelopeBatchSubmission;
            KY_Soap_Test.ServiceReference1.BatchSubmitTransactionResponse retVal = ((KY_Soap_Test.ServiceReference1.BatchWebServiceInterface)(this)).SubmitFile(inValue);
            return retVal.COREEnvelopeBatchSubmissionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KY_Soap_Test.ServiceReference1.BatchSubmitTransactionResponse> KY_Soap_Test.ServiceReference1.BatchWebServiceInterface.SubmitFileAsync(KY_Soap_Test.ServiceReference1.BatchSubmitTransactionRequest request) {
            return base.Channel.SubmitFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<KY_Soap_Test.ServiceReference1.BatchSubmitTransactionResponse> SubmitFileAsync(KY_Soap_Test.ServiceReference1.CAQHRequestField COREEnvelopeBatchSubmission) {
            KY_Soap_Test.ServiceReference1.BatchSubmitTransactionRequest inValue = new KY_Soap_Test.ServiceReference1.BatchSubmitTransactionRequest();
            inValue.COREEnvelopeBatchSubmission = COREEnvelopeBatchSubmission;
            return ((KY_Soap_Test.ServiceReference1.BatchWebServiceInterface)(this)).SubmitFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KY_Soap_Test.ServiceReference1.BatchResultsRetrievalTransactionResponse KY_Soap_Test.ServiceReference1.BatchWebServiceInterface.DownloadFile(KY_Soap_Test.ServiceReference1.BatchResultsRetrievalTransactionRequest request) {
            return base.Channel.DownloadFile(request);
        }
        
        public KY_Soap_Test.ServiceReference1.CAQHResponseField DownloadFile(KY_Soap_Test.ServiceReference1.CAQHRequestField COREEnvelopeBatchResultsRetrievalRequest) {
            KY_Soap_Test.ServiceReference1.BatchResultsRetrievalTransactionRequest inValue = new KY_Soap_Test.ServiceReference1.BatchResultsRetrievalTransactionRequest();
            inValue.COREEnvelopeBatchResultsRetrievalRequest = COREEnvelopeBatchResultsRetrievalRequest;
            KY_Soap_Test.ServiceReference1.BatchResultsRetrievalTransactionResponse retVal = ((KY_Soap_Test.ServiceReference1.BatchWebServiceInterface)(this)).DownloadFile(inValue);
            return retVal.COREEnvelopeBatchResultsRetrievalResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KY_Soap_Test.ServiceReference1.BatchResultsRetrievalTransactionResponse> KY_Soap_Test.ServiceReference1.BatchWebServiceInterface.DownloadFileAsync(KY_Soap_Test.ServiceReference1.BatchResultsRetrievalTransactionRequest request) {
            return base.Channel.DownloadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<KY_Soap_Test.ServiceReference1.BatchResultsRetrievalTransactionResponse> DownloadFileAsync(KY_Soap_Test.ServiceReference1.CAQHRequestField COREEnvelopeBatchResultsRetrievalRequest) {
            KY_Soap_Test.ServiceReference1.BatchResultsRetrievalTransactionRequest inValue = new KY_Soap_Test.ServiceReference1.BatchResultsRetrievalTransactionRequest();
            inValue.COREEnvelopeBatchResultsRetrievalRequest = COREEnvelopeBatchResultsRetrievalRequest;
            return ((KY_Soap_Test.ServiceReference1.BatchWebServiceInterface)(this)).DownloadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KY_Soap_Test.ServiceReference1.BatchSubmitAckRetrievalTransactionResponse KY_Soap_Test.ServiceReference1.BatchWebServiceInterface.DownloadAckFile(KY_Soap_Test.ServiceReference1.BatchSubmitAckRetrievalTransactionRequest request) {
            return base.Channel.DownloadAckFile(request);
        }
        
        public KY_Soap_Test.ServiceReference1.CAQHResponseField DownloadAckFile(KY_Soap_Test.ServiceReference1.CAQHRequestField COREEnvelopeBatchSubmissionAckRetrievalRequest) {
            KY_Soap_Test.ServiceReference1.BatchSubmitAckRetrievalTransactionRequest inValue = new KY_Soap_Test.ServiceReference1.BatchSubmitAckRetrievalTransactionRequest();
            inValue.COREEnvelopeBatchSubmissionAckRetrievalRequest = COREEnvelopeBatchSubmissionAckRetrievalRequest;
            KY_Soap_Test.ServiceReference1.BatchSubmitAckRetrievalTransactionResponse retVal = ((KY_Soap_Test.ServiceReference1.BatchWebServiceInterface)(this)).DownloadAckFile(inValue);
            return retVal.COREEnvelopeBatchSubmissionAckRetrievalResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KY_Soap_Test.ServiceReference1.BatchSubmitAckRetrievalTransactionResponse> KY_Soap_Test.ServiceReference1.BatchWebServiceInterface.DownloadAckFileAsync(KY_Soap_Test.ServiceReference1.BatchSubmitAckRetrievalTransactionRequest request) {
            return base.Channel.DownloadAckFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<KY_Soap_Test.ServiceReference1.BatchSubmitAckRetrievalTransactionResponse> DownloadAckFileAsync(KY_Soap_Test.ServiceReference1.CAQHRequestField COREEnvelopeBatchSubmissionAckRetrievalRequest) {
            KY_Soap_Test.ServiceReference1.BatchSubmitAckRetrievalTransactionRequest inValue = new KY_Soap_Test.ServiceReference1.BatchSubmitAckRetrievalTransactionRequest();
            inValue.COREEnvelopeBatchSubmissionAckRetrievalRequest = COREEnvelopeBatchSubmissionAckRetrievalRequest;
            return ((KY_Soap_Test.ServiceReference1.BatchWebServiceInterface)(this)).DownloadAckFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KY_Soap_Test.ServiceReference1.GetDownloadFilesByPayloadIDResponse KY_Soap_Test.ServiceReference1.BatchWebServiceInterface.GetDownloadFilesByPayloadID(KY_Soap_Test.ServiceReference1.GetDownloadFilesByPayloadIDRequest request) {
            return base.Channel.GetDownloadFilesByPayloadID(request);
        }
        
        public string GetDownloadFilesByPayloadID(string PayloadID) {
            KY_Soap_Test.ServiceReference1.GetDownloadFilesByPayloadIDRequest inValue = new KY_Soap_Test.ServiceReference1.GetDownloadFilesByPayloadIDRequest();
            inValue.PayloadID = PayloadID;
            KY_Soap_Test.ServiceReference1.GetDownloadFilesByPayloadIDResponse retVal = ((KY_Soap_Test.ServiceReference1.BatchWebServiceInterface)(this)).GetDownloadFilesByPayloadID(inValue);
            return retVal.GetDownloadFilesByPayloadIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KY_Soap_Test.ServiceReference1.GetDownloadFilesByPayloadIDResponse> KY_Soap_Test.ServiceReference1.BatchWebServiceInterface.GetDownloadFilesByPayloadIDAsync(KY_Soap_Test.ServiceReference1.GetDownloadFilesByPayloadIDRequest request) {
            return base.Channel.GetDownloadFilesByPayloadIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<KY_Soap_Test.ServiceReference1.GetDownloadFilesByPayloadIDResponse> GetDownloadFilesByPayloadIDAsync(string PayloadID) {
            KY_Soap_Test.ServiceReference1.GetDownloadFilesByPayloadIDRequest inValue = new KY_Soap_Test.ServiceReference1.GetDownloadFilesByPayloadIDRequest();
            inValue.PayloadID = PayloadID;
            return ((KY_Soap_Test.ServiceReference1.BatchWebServiceInterface)(this)).GetDownloadFilesByPayloadIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KY_Soap_Test.ServiceReference1.GetDownloadFilesByTPIDResponse KY_Soap_Test.ServiceReference1.BatchWebServiceInterface.GetDownloadFilesByTPID(KY_Soap_Test.ServiceReference1.GetDownloadFilesByTPIDRequest request) {
            return base.Channel.GetDownloadFilesByTPID(request);
        }
        
        public string GetDownloadFilesByTPID() {
            KY_Soap_Test.ServiceReference1.GetDownloadFilesByTPIDRequest inValue = new KY_Soap_Test.ServiceReference1.GetDownloadFilesByTPIDRequest();
            KY_Soap_Test.ServiceReference1.GetDownloadFilesByTPIDResponse retVal = ((KY_Soap_Test.ServiceReference1.BatchWebServiceInterface)(this)).GetDownloadFilesByTPID(inValue);
            return retVal.GetDownloadFilesByTPIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KY_Soap_Test.ServiceReference1.GetDownloadFilesByTPIDResponse> KY_Soap_Test.ServiceReference1.BatchWebServiceInterface.GetDownloadFilesByTPIDAsync(KY_Soap_Test.ServiceReference1.GetDownloadFilesByTPIDRequest request) {
            return base.Channel.GetDownloadFilesByTPIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<KY_Soap_Test.ServiceReference1.GetDownloadFilesByTPIDResponse> GetDownloadFilesByTPIDAsync() {
            KY_Soap_Test.ServiceReference1.GetDownloadFilesByTPIDRequest inValue = new KY_Soap_Test.ServiceReference1.GetDownloadFilesByTPIDRequest();
            return ((KY_Soap_Test.ServiceReference1.BatchWebServiceInterface)(this)).GetDownloadFilesByTPIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KY_Soap_Test.ServiceReference1.GetDownloadFilesByUserIDResponse KY_Soap_Test.ServiceReference1.BatchWebServiceInterface.GetDownloadFilesByUserID(KY_Soap_Test.ServiceReference1.GetDownloadFilesByUserIDRequest request) {
            return base.Channel.GetDownloadFilesByUserID(request);
        }
        
        public string GetDownloadFilesByUserID() {
            KY_Soap_Test.ServiceReference1.GetDownloadFilesByUserIDRequest inValue = new KY_Soap_Test.ServiceReference1.GetDownloadFilesByUserIDRequest();
            KY_Soap_Test.ServiceReference1.GetDownloadFilesByUserIDResponse retVal = ((KY_Soap_Test.ServiceReference1.BatchWebServiceInterface)(this)).GetDownloadFilesByUserID(inValue);
            return retVal.GetDownloadFilesByUserIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KY_Soap_Test.ServiceReference1.GetDownloadFilesByUserIDResponse> KY_Soap_Test.ServiceReference1.BatchWebServiceInterface.GetDownloadFilesByUserIDAsync(KY_Soap_Test.ServiceReference1.GetDownloadFilesByUserIDRequest request) {
            return base.Channel.GetDownloadFilesByUserIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<KY_Soap_Test.ServiceReference1.GetDownloadFilesByUserIDResponse> GetDownloadFilesByUserIDAsync() {
            KY_Soap_Test.ServiceReference1.GetDownloadFilesByUserIDRequest inValue = new KY_Soap_Test.ServiceReference1.GetDownloadFilesByUserIDRequest();
            return ((KY_Soap_Test.ServiceReference1.BatchWebServiceInterface)(this)).GetDownloadFilesByUserIDAsync(inValue);
        }
    }
}
